#!/bin/bash

dir=`dirname $0`

mongoexport -d mean-test -c cities > $dir/cities.json
mongoexport -d mean-test -c flights > $dir/flights.json
mongoexport -d mean-test -c orders > $dir/orders.json
mongoexport -d mean-test -c users > $dir/users.json
