#!/bin/bash

dir=`dirname $0`

mongoimport -d mean-dev -c cities --drop < $dir/cities.json
mongoimport -d mean-dev -c flights --drop < $dir/flights.json
mongoimport -d mean-dev -c orders --drop < $dir/orders.json
mongoimport -d mean-dev -c users --drop < $dir/users.json
